FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY . .

# Ensure upload directory exists
RUN mkdir -p uploads

EXPOSE 5000

ENV NODE_ENV=production

CMD ["npm", "start"]
